id: PDCA6C9B5
initial_creation_type: input
source_metadata:
  title: Yamāntaka Series
  language: de
  description: 'Texts related to Yamāntaka (gshin rje gshed), the wrathful form of
    Mañjuśrī:'
  volume:
    6866b77776214656b44df1f99bc40090:
      title: Daily Practice of Mañjuśrī Yamāntaka
      parent: Sādhanas
    b152d1138be64f478d945dd128980396:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Sādhanas
created_at: '2022-03-01T06:35:53.229615'
last_modified_at: '2022-03-01T06:35:53.229618'
